name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: 'v'
version-resolver:
  major:
    labels: [ 'breaking' ]
  minor:
    labels: [ 'feature', 'enhancement' ]
  patch:
    labels: [ 'bug', 'fix', 'documentation', 'refactor', 'performance', 'test', 'ci', 'build', 'chore' ]
  default: patch
categories:
  - title: '🚀 Features'
    labels: [ 'feature', 'enhancement' ]
  - title: '🐛 Fixes'
    labels: [ 'bug', 'fix' ]
  - title: '🧰 Maintenance'
    labels: [ 'chore', 'build', 'ci', 'refactor', 'performance', 'test' ]
  - title: '📝 Documentation'
    labels: [ 'documentation' ]
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## Changes
  $CHANGES

autolabeler:
  - label: 'feature'
    title:
      - '/^feat(\(.*\))?:/i'
  - label: 'bug'
    title:
      - '/^fix(\(.*\))?:/i'
  - label: 'documentation'
    title:
      - '/^docs(\(.*\))?:/i'
  - label: 'refactor'
    title:
      - '/^refactor(\(.*\))?:/i'
  - label: 'performance'
    title:
      - '/^perf(\(.*\))?:/i'
  - label: 'test'
    title:
      - '/^test(\(.*\))?:/i'
  - label: 'ci'
    title:
      - '/^ci(\(.*\))?:/i'
  - label: 'build'
    title:
      - '/^build(\(.*\))?:/i'
  - label: 'chore'
    title:
      - '/^chore(\(.*\))?:/i'
