version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:5.0
    container_name: chatbot-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: smartroute-chatbot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - chatbot-network

  # Chatbot Backend API
  chatbot-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chatbot-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/smartroute-chatbot?authSource=admin
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      USE_OPENAI: ${USE_OPENAI:-false}
    depends_on:
      - mongodb
    networks:
      - chatbot-network
    volumes:
      - ./server/logs:/app/logs

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: chatbot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./client/build:/usr/share/nginx/html:ro
    depends_on:
      - chatbot-api
    networks:
      - chatbot-network

volumes:
  mongodb_data:
    driver: local

networks:
  chatbot-network:
    driver: bridge