version: '3.9'

services:
  api:
    build:
      context: ./server
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - web

  nginx:
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge

