version: '3.9'

services:
  api:
    image: ghcr.io/smartroutelogistics/chatbot-server:latest
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - web

  nginx:
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deployment/certbot/conf:/etc/letsencrypt
      - ./deployment/certbot/www:/var/www/certbot
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge

