version: '3.9'

services:
  api:
    build:
      context: ./server
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - web

  nginx:
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deployment/certbot/conf:/etc/letsencrypt
      - ./deployment/certbot/www:/var/www/certbot
    restart: unless-stopped
    networks:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./deployment/certbot/conf:/etc/letsencrypt
      - ./deployment/certbot/www:/var/www/certbot
    entrypoint: tail -f /dev/null

networks:
  web:
    driver: bridge
