name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Install client and server deps
        run: npm run install-all

      - name: Lint (if configured)
        run: |
          echo "Skipping lint if not configured"
        shell: bash

      - name: Test server
        run: npm --prefix server test --if-present

      - name: Build client
        env:
          CI: true
        run: npm --prefix client run build

      - name: Smoke check server starts
        run: |
          node -e "require('fs').existsSync('server/index.js') && console.log('server entry present')"

